services:
  - type: web
    name: webrtc-chat
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
